/**
 * Example semi-automated test
 *
 * This test automates navigation but pauses for manual verification.
 * Run with: PWDEBUG=1 npx ts-node tests/e2e/example.test.ts
 *
 * Or run yarn start:debug first, then use the codegen script to generate
 * the click/navigation code below.
 */

import { chromium, Page } from 'playwright';

const CDP_URL = 'http://localhost:9222';

async function runTest() {
  const browser = await chromium.connectOverCDP(CDP_URL);
  const page = browser.contexts()[0].pages()[0];

  // Example: Navigate to a tab and pause for manual verification
  // Replace these selectors with ones generated by codegen

  // --- PASTE GENERATED CODE HERE ---
  // await page.click('[data-testid="some-button"]');
  // await page.pause(); // Manual verification point

  // await page.fill('[data-testid="some-input"]', 'test value');
  // await page.pause(); // Verify input worked

  // --- END GENERATED CODE ---

  // Keep page reference for manual interaction
  await manualVerification(page, 'Verify the UI looks correct');

  await browser.close();
}

async function manualVerification(page: Page, instruction: string) {
  console.log(`\n=== MANUAL VERIFICATION ===`);
  console.log(instruction);
  console.log('Press Resume in Inspector when done\n');
  await page.pause();
}

runTest().catch(console.error);
